version: '3.1'

services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - MYSQL_ROOT_PASSWORD=examplepass
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=exampleuser
      - PMA_PASSWORD=examplepass
      - PMA_ARBITRARY=1

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025

volumes:
  wordpress:
  db:
